-- =============================================================================
--                   HYPRLAND ANA YAPILANDIRMA DOSYASI (LUA)
-- =============================================================================
-- Bu dosya, alt modülleri bir araya getiren ana merkezdir.
-- Ayarları değiştirmek için ilgili modül dosyalarına göz atabilirsiniz.

-- Otomatik oluşturulan ilk kurulum uyarısını kapatır.
-- hl.config({ autogenerated = false }) 

-- -----------------------------------------------------------------------------
-- MODÜLLERİN YÜKLENMESİ
-- -----------------------------------------------------------------------------
-- `~/.config/hypr/` altındaki ilgili .lua dosyalarını sırayla içeri aktarıyoruz.

require("monitors")     -- Ekran çözünürlüğü ve yerleşimi
require("env_vars")     -- Çevre (Environment) değişkenleri
require("programs")     -- Varsayılan uygulamalar ve Autostart (Başlangıç)
require("look_feel")    -- Görsel ayarlar (Animasyonlar, kenarlıklar, boşluklar)
require("input_rules")  -- Klavye, fare, touchpad ve hareket ayarları
require("binds")        -- Klavye kısayolları (Keybindings)
require("rules")        -- Pencere ve katman kuralları (Window/Layer Rules)
